name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change based on your project

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Setup S3 cmd
        uses: s3-actions/s3cmd@v1.6.1
        with:
           provider: aws
           region: ap-south-1
           access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to S3
        run: s3cmd sync ./dist/ s3://caam-bucket/ --delete-removed --acl-public

       

      - name: Invalidate CloudFront Cache (via CLI)
        run: |
           aws cloudfront create-invalidation \
           --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
           --paths "/*"
        env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}


